### ISSUE TITLE
Does it support these?

### ISSUE THREAD

**Issue by Saeed-Bahrami** [Meteor-Community-Packages/react-router-ssr#7]
Does it support these? 
1 - react router 5
2 - meteor 1.11

**Comment by StorytellerCZ** [comment]
Wasn't sure about react-router, but since it is in the reference implementation in the readme the answer is yes.

**Comment by StorytellerCZ** [comment]
Just a quick update, there seems to be a potential bug with `fast-render`, already made a PR to fix that.

**Comment by Saeed-Bahrami** [comment]
@StorytellerCZ  Does it support [loadable-components](https://loadable-components.com/)?

**Comment by Saeed-Bahrami** [comment]
> Just a quick update, there seems to be a potential bug with fast-render, already made a PR to fix that.
About when does it mearge?
Because no matter how much I tried, I could not use it.

**Comment by copleykj** [comment]
To update the bug in fast-render portion of this discussion. The issue actually appears to be in the inject-data package.

Basically what is happening is that both the `server-render` package and the `inject-data` package use `WebAppInternals.registerBoilerplateDataCallback` to register a callback when the server gets a request. The problem lies in the fact that for some reason the on registered by the `inject-data` package gets run first, and therefor the `fast-render` package which relies on `server-render` has not had a chance to collect all the published data and hand if off to the `inject-data` package before it modifies the html to send down.

I have a fix for this ready to go but `fast-render` and `inject-data` are no longer being actively maintained and so I'm working to move them under Meteor-Community-Packages so that we can get this all sorted out.

**Comment by copleykj** [comment]
V3.0.0 just released and works with the latest react, react-router-dom and helmet. As far as loadable components I can't say for certain, but I think your best bet is going to be the `npdev:react-loadable` package. Give it a whirl and let us know how it turns out.
